const SCREENS = {
  ABOUT: 'ABOUT',
  INTRO: 'INTRO',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOTPASS: 'FORGOTPASS',
  HOME: 'HOME',
  ORDERS: 'ORDERS',
  WISHLIST: 'WISHLIST',
  PROFILE: 'PROFILE',
  SMART: 'SMART',
  NOTIFICATION: 'NOTIFICATION',
  ADD: 'ADD',
  AI: 'AI',
  CONFIRMLOGIN: 'CONFIRMLOGIN',
  CONFIRMEMAIL: 'CONFIRMEMAIL'


};

export default SCREENS;
